/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/kv.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/kv.pb-c.h"
void   kv__set_request__init
                     (Kv__SetRequest         *message)
{
  static const Kv__SetRequest init_value = KV__SET_REQUEST__INIT;
  *message = init_value;
}
size_t kv__set_request__get_packed_size
                     (const Kv__SetRequest *message)
{
  assert(message->base.descriptor == &kv__set_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__set_request__pack
                     (const Kv__SetRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__set_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__set_request__pack_to_buffer
                     (const Kv__SetRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__set_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__SetRequest *
       kv__set_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__SetRequest *)
     protobuf_c_message_unpack (&kv__set_request__descriptor,
                                allocator, len, data);
}
void   kv__set_request__free_unpacked
                     (Kv__SetRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__set_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__set_response__init
                     (Kv__SetResponse         *message)
{
  static const Kv__SetResponse init_value = KV__SET_RESPONSE__INIT;
  *message = init_value;
}
size_t kv__set_response__get_packed_size
                     (const Kv__SetResponse *message)
{
  assert(message->base.descriptor == &kv__set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__set_response__pack
                     (const Kv__SetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__set_response__pack_to_buffer
                     (const Kv__SetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__SetResponse *
       kv__set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__SetResponse *)
     protobuf_c_message_unpack (&kv__set_response__descriptor,
                                allocator, len, data);
}
void   kv__set_response__free_unpacked
                     (Kv__SetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__get_request__init
                     (Kv__GetRequest         *message)
{
  static const Kv__GetRequest init_value = KV__GET_REQUEST__INIT;
  *message = init_value;
}
size_t kv__get_request__get_packed_size
                     (const Kv__GetRequest *message)
{
  assert(message->base.descriptor == &kv__get_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__get_request__pack
                     (const Kv__GetRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__get_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__get_request__pack_to_buffer
                     (const Kv__GetRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__get_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__GetRequest *
       kv__get_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__GetRequest *)
     protobuf_c_message_unpack (&kv__get_request__descriptor,
                                allocator, len, data);
}
void   kv__get_request__free_unpacked
                     (Kv__GetRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__get_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__value__init
                     (Kv__Value         *message)
{
  static const Kv__Value init_value = KV__VALUE__INIT;
  *message = init_value;
}
size_t kv__value__get_packed_size
                     (const Kv__Value *message)
{
  assert(message->base.descriptor == &kv__value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__value__pack
                     (const Kv__Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__value__pack_to_buffer
                     (const Kv__Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__Value *
       kv__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__Value *)
     protobuf_c_message_unpack (&kv__value__descriptor,
                                allocator, len, data);
}
void   kv__value__free_unpacked
                     (Kv__Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kv__get_response__values_entry__init
                     (Kv__GetResponse__ValuesEntry         *message)
{
  static const Kv__GetResponse__ValuesEntry init_value = KV__GET_RESPONSE__VALUES_ENTRY__INIT;
  *message = init_value;
}
void   kv__get_response__init
                     (Kv__GetResponse         *message)
{
  static const Kv__GetResponse init_value = KV__GET_RESPONSE__INIT;
  *message = init_value;
}
size_t kv__get_response__get_packed_size
                     (const Kv__GetResponse *message)
{
  assert(message->base.descriptor == &kv__get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kv__get_response__pack
                     (const Kv__GetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kv__get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kv__get_response__pack_to_buffer
                     (const Kv__GetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kv__get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kv__GetResponse *
       kv__get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kv__GetResponse *)
     protobuf_c_message_unpack (&kv__get_response__descriptor,
                                allocator, len, data);
}
void   kv__get_response__free_unpacked
                     (Kv__GetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kv__get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor kv__set_request__field_descriptors[4] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__SetRequest, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kv__SetRequest, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expireTime",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Kv__SetRequest, expiretime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kv__SetRequest, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__set_request__field_indices_by_name[] = {
  3,   /* field[3] = data */
  2,   /* field[2] = expireTime */
  1,   /* field[1] = flags */
  0,   /* field[0] = key */
};
static const ProtobufCIntRange kv__set_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor kv__set_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.SetRequest",
  "SetRequest",
  "Kv__SetRequest",
  "kv",
  sizeof(Kv__SetRequest),
  4,
  kv__set_request__field_descriptors,
  kv__set_request__field_indices_by_name,
  1,  kv__set_request__number_ranges,
  (ProtobufCMessageInit) kv__set_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__set_response__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Kv__SetResponse, status),
    &kv__status_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__set_response__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange kv__set_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor kv__set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.SetResponse",
  "SetResponse",
  "Kv__SetResponse",
  "kv",
  sizeof(Kv__SetResponse),
  1,
  kv__set_response__field_descriptors,
  kv__set_response__field_indices_by_name,
  1,  kv__set_response__number_ranges,
  (ProtobufCMessageInit) kv__set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__get_request__field_descriptors[1] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Kv__GetRequest, n_keys),
    offsetof(Kv__GetRequest, keys),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__get_request__field_indices_by_name[] = {
  0,   /* field[0] = keys */
};
static const ProtobufCIntRange kv__get_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor kv__get_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.GetRequest",
  "GetRequest",
  "Kv__GetRequest",
  "kv",
  sizeof(Kv__GetRequest),
  1,
  kv__get_request__field_descriptors,
  kv__get_request__field_indices_by_name,
  1,  kv__get_request__number_ranges,
  (ProtobufCMessageInit) kv__get_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__value__field_descriptors[2] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kv__Value, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kv__Value, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__value__field_indices_by_name[] = {
  0,   /* field[0] = data */
  1,   /* field[1] = flags */
};
static const ProtobufCIntRange kv__value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kv__value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.Value",
  "Value",
  "Kv__Value",
  "kv",
  sizeof(Kv__Value),
  2,
  kv__value__field_descriptors,
  kv__value__field_indices_by_name,
  1,  kv__value__number_ranges,
  (ProtobufCMessageInit) kv__value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__get_response__values_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kv__GetResponse__ValuesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Kv__GetResponse__ValuesEntry, value),
    &kv__value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__get_response__values_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange kv__get_response__values_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor kv__get_response__values_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.GetResponse.ValuesEntry",
  "ValuesEntry",
  "Kv__GetResponse__ValuesEntry",
  "kv",
  sizeof(Kv__GetResponse__ValuesEntry),
  2,
  kv__get_response__values_entry__field_descriptors,
  kv__get_response__values_entry__field_indices_by_name,
  1,  kv__get_response__values_entry__number_ranges,
  (ProtobufCMessageInit) kv__get_response__values_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kv__get_response__field_descriptors[1] =
{
  {
    "values",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Kv__GetResponse, n_values),
    offsetof(Kv__GetResponse, values),
    &kv__get_response__values_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kv__get_response__field_indices_by_name[] = {
  0,   /* field[0] = values */
};
static const ProtobufCIntRange kv__get_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor kv__get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kv.GetResponse",
  "GetResponse",
  "Kv__GetResponse",
  "kv",
  sizeof(Kv__GetResponse),
  1,
  kv__get_response__field_descriptors,
  kv__get_response__field_indices_by_name,
  1,  kv__get_response__number_ranges,
  (ProtobufCMessageInit) kv__get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue kv__status_code__enum_values_by_number[2] =
{
  { "ERROR", "KV__STATUS_CODE__ERROR", 0 },
  { "STORED", "KV__STATUS_CODE__STORED", 1 },
};
static const ProtobufCIntRange kv__status_code__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex kv__status_code__enum_values_by_name[2] =
{
  { "ERROR", 0 },
  { "STORED", 1 },
};
const ProtobufCEnumDescriptor kv__status_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "kv.StatusCode",
  "StatusCode",
  "Kv__StatusCode",
  "kv",
  2,
  kv__status_code__enum_values_by_number,
  2,
  kv__status_code__enum_values_by_name,
  1,
  kv__status_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
