/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/kv.proto */

#ifndef PROTOBUF_C_proto_2fkv_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fkv_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Kv__SetRequest Kv__SetRequest;
typedef struct Kv__SetResponse Kv__SetResponse;
typedef struct Kv__GetRequest Kv__GetRequest;
typedef struct Kv__Value Kv__Value;
typedef struct Kv__GetResponse Kv__GetResponse;
typedef struct Kv__GetResponse__ValuesEntry Kv__GetResponse__ValuesEntry;


/* --- enums --- */

typedef enum _Kv__StatusCode {
  KV__STATUS_CODE__ERROR = 0,
  KV__STATUS_CODE__STORED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(KV__STATUS_CODE)
} Kv__StatusCode;

/* --- messages --- */

struct  Kv__SetRequest
{
  ProtobufCMessage base;
  char *key;
  uint32_t flags;
  int64_t expiretime;
  ProtobufCBinaryData data;
};
#define KV__SET_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__set_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, {0,NULL} }


struct  Kv__SetResponse
{
  ProtobufCMessage base;
  Kv__StatusCode status;
};
#define KV__SET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__set_response__descriptor) \
    , KV__STATUS_CODE__ERROR }


struct  Kv__GetRequest
{
  ProtobufCMessage base;
  size_t n_keys;
  char **keys;
};
#define KV__GET_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__get_request__descriptor) \
    , 0,NULL }


struct  Kv__Value
{
  ProtobufCMessage base;
  ProtobufCBinaryData data;
  uint32_t flags;
};
#define KV__VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__value__descriptor) \
    , {0,NULL}, 0 }


struct  Kv__GetResponse__ValuesEntry
{
  ProtobufCMessage base;
  char *key;
  Kv__Value *value;
};
#define KV__GET_RESPONSE__VALUES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__get_response__values_entry__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  Kv__GetResponse
{
  ProtobufCMessage base;
  size_t n_values;
  Kv__GetResponse__ValuesEntry **values;
};
#define KV__GET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kv__get_response__descriptor) \
    , 0,NULL }


/* Kv__SetRequest methods */
void   kv__set_request__init
                     (Kv__SetRequest         *message);
size_t kv__set_request__get_packed_size
                     (const Kv__SetRequest   *message);
size_t kv__set_request__pack
                     (const Kv__SetRequest   *message,
                      uint8_t             *out);
size_t kv__set_request__pack_to_buffer
                     (const Kv__SetRequest   *message,
                      ProtobufCBuffer     *buffer);
Kv__SetRequest *
       kv__set_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__set_request__free_unpacked
                     (Kv__SetRequest *message,
                      ProtobufCAllocator *allocator);
/* Kv__SetResponse methods */
void   kv__set_response__init
                     (Kv__SetResponse         *message);
size_t kv__set_response__get_packed_size
                     (const Kv__SetResponse   *message);
size_t kv__set_response__pack
                     (const Kv__SetResponse   *message,
                      uint8_t             *out);
size_t kv__set_response__pack_to_buffer
                     (const Kv__SetResponse   *message,
                      ProtobufCBuffer     *buffer);
Kv__SetResponse *
       kv__set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__set_response__free_unpacked
                     (Kv__SetResponse *message,
                      ProtobufCAllocator *allocator);
/* Kv__GetRequest methods */
void   kv__get_request__init
                     (Kv__GetRequest         *message);
size_t kv__get_request__get_packed_size
                     (const Kv__GetRequest   *message);
size_t kv__get_request__pack
                     (const Kv__GetRequest   *message,
                      uint8_t             *out);
size_t kv__get_request__pack_to_buffer
                     (const Kv__GetRequest   *message,
                      ProtobufCBuffer     *buffer);
Kv__GetRequest *
       kv__get_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__get_request__free_unpacked
                     (Kv__GetRequest *message,
                      ProtobufCAllocator *allocator);
/* Kv__Value methods */
void   kv__value__init
                     (Kv__Value         *message);
size_t kv__value__get_packed_size
                     (const Kv__Value   *message);
size_t kv__value__pack
                     (const Kv__Value   *message,
                      uint8_t             *out);
size_t kv__value__pack_to_buffer
                     (const Kv__Value   *message,
                      ProtobufCBuffer     *buffer);
Kv__Value *
       kv__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__value__free_unpacked
                     (Kv__Value *message,
                      ProtobufCAllocator *allocator);
/* Kv__GetResponse__ValuesEntry methods */
void   kv__get_response__values_entry__init
                     (Kv__GetResponse__ValuesEntry         *message);
/* Kv__GetResponse methods */
void   kv__get_response__init
                     (Kv__GetResponse         *message);
size_t kv__get_response__get_packed_size
                     (const Kv__GetResponse   *message);
size_t kv__get_response__pack
                     (const Kv__GetResponse   *message,
                      uint8_t             *out);
size_t kv__get_response__pack_to_buffer
                     (const Kv__GetResponse   *message,
                      ProtobufCBuffer     *buffer);
Kv__GetResponse *
       kv__get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kv__get_response__free_unpacked
                     (Kv__GetResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Kv__SetRequest_Closure)
                 (const Kv__SetRequest *message,
                  void *closure_data);
typedef void (*Kv__SetResponse_Closure)
                 (const Kv__SetResponse *message,
                  void *closure_data);
typedef void (*Kv__GetRequest_Closure)
                 (const Kv__GetRequest *message,
                  void *closure_data);
typedef void (*Kv__Value_Closure)
                 (const Kv__Value *message,
                  void *closure_data);
typedef void (*Kv__GetResponse__ValuesEntry_Closure)
                 (const Kv__GetResponse__ValuesEntry *message,
                  void *closure_data);
typedef void (*Kv__GetResponse_Closure)
                 (const Kv__GetResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    kv__status_code__descriptor;
extern const ProtobufCMessageDescriptor kv__set_request__descriptor;
extern const ProtobufCMessageDescriptor kv__set_response__descriptor;
extern const ProtobufCMessageDescriptor kv__get_request__descriptor;
extern const ProtobufCMessageDescriptor kv__value__descriptor;
extern const ProtobufCMessageDescriptor kv__get_response__descriptor;
extern const ProtobufCMessageDescriptor kv__get_response__values_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fkv_2eproto__INCLUDED */
